modules:
  - type: files
    files:
      - source: system
        destination: /
      - source: 60-custom.just
        destination: /usr/share/ublue-os/just/60-custom.just

      # these configuration files live in two different directories?
      - source: user-dirs
        destination: /etc/xdg/
      - source: user-dirs
        destination: /etc/

  - type: dnf
    repos:
      cleanup: false
      copr:
        - atim/starship
        - ublue-os/packages
        - monkeygold/nautilus-open-any-terminal
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://mise.jdx.dev/rpm/mise.repo
    install:
      packages:
        # editors
        - micro

        # term emus
        # - kitty
        - foot
        # - ghostty

        # termbling
        - fish
        - starship
        - fastfetch
        - fortune-mod
        - cowsay
        - lolcat
        - cava

        # devtools
        - mise
        - moby-engine
        - gcc
        - libgit2
        - nmap
        - android-tools

        # realtime
        - realtime-setup

        - quickemu # virt

        # misc
        - python
        - rsync
        - rclone
        - tailscale
        - ffmpeg

        - bazaar

        - nautilus-open-any-terminal
    group-install:
      packages:
        - virtualization
    remove:
      packages:
        - firefox # default firefox removed in favor of flatpak

  - type: default-flatpaks
    source: ghcr.io/blue-build/modules/default-flatpaks
    configurations:
      - scope: user
        install:
          - com.brave.Browser
          - com.github.tchx84.Flatseal
          - page.kramo.Cartridges
          - io.itch.itch
          # - com.valvesoftware.Steam
          # - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
          # - io.github.Foldex.AdwSteamGtk
          - com.usebottles.bottles
          - org.prismlauncher.PrismLauncher
          - fr.handbrake.ghb
          - io.mpv.Mpv
          - com.logseq.Logseq
          - md.obsidian.Obsidian
          - com.obsproject.Studio
          - com.google.AndroidStudio
          - com.jetbrains.IntelliJ-IDEA-Community
          - io.github.dweymouth.supersonic
          - io.gitlab.librewolf-community
          - org.mozilla.firefox
          - nl.hjdskes.gcolor3
          - io.github.swordpuffin.rewaita
          - org.audacityteam.Audacity
          - org.blender.Blender
          - org.kde.kdenlive
          - org.shotcut.Shotcut
          - org.kde.krita
          - org.fedoraproject.MediaWriter
          - org.freedesktop.Piper
          - org.gnome.Loupe
          - org.gnome.World.PikaBackup
          - org.musicbrainz.Picard
          - org.speedcrunch.SpeedCrunch
          - dev.zed.Zed
          - re.sonny.Junction
          - page.tesk.Refine
          - dev.deedles.Trayscale
          - com.github.zocker_160.SyncThingy
          - org.jeffvli.feishin

  - type: script
    scripts:
      - maplemono.nu
      - gitbutler.nu
      - bibata.nu
      # - feishin.nu

  - type: systemd
    system:
      enabled:
        - mount-on-boot.service
        - tailscaled.service
      masked:
        # needed for realtime on gnome 45+ according to yabridge readme
        - rtkit-daemon.service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - SpaceMono
        - IBMPlexMono
        - Iosevka
        - IosevkaTerm
        - iA-Writer
        - 0xProto
        - AdwaitaMono
        - Recursive
      google-fonts:
        - Roboto
        - Open Sans
        - Work Sans
        - Outfit
        - Space Grotesk
        - Inter
        - Atkinson Hyperlegible
        - IBM Plex Sans
        - Vollkorn
        - EB Garamond

  - type: chezmoi
    repository: "git@github.com:xynydev/dots.git"

  - type: signing
